Group: group authentication, mutual authentication
A-APT/DuckBox-SmartContract pull request #1
Opened 2022-03-04 12:05 UTC by Hongji0611

## 개요
- 그룹 인증과 그룹원 상호 인증

## 상세내용
- 그룹이 생성될 때마다, Group contract가 하나 생성됩니다.
- 그룹장을 제외한 다른 2명이 그룹에 대한 인증을 해주어야 그룹 인증이 완료됩니다.
- 그룹장, 그룹 생성을 승인해준 2명은 isValid가 True입니다.
- 그룹에 가입하려고 할 때, 사용자의 DID가 필요합니다.
- 이미 그룹에 가입된 사람만 가입 요청 사용자를 승인해줄 수 있습니다.

## 리뷰어가 확인할 사항
- Test를 위한 `truffle-assertions`를 설치했습니다. `npm install truffle-assertions` (@0JIEUN0👍) ([참고](https://gitlab.ifi.uzh.ch/rodrigues/scflare/-/tree/master/Truffle/truffle-assertions))

## 기타
- requestMember() 에서 똑같은 사용자가 여러 번 가입을 요청하는 경우와 approveMember()에서 똑같은 승인자가 여러 번 승인을 하려는 경우의 예외 처리도 컨트랙트에서 해야 할 지 혹은 서버나 클라이언트에서 처리할 지 의견 남겨주세요!

2022-03-04 12:40 UTC, 0JIEUN0 requested changes
- Group 도 Ballot 에서 하고 있는 것처럼 status 로 Group 의 현 상태를 보여주는 구조를 써도 좋을 것 같아요!
- '똑같은 승인자가 여러 번 승인을 하려는 경우의 예외 처리' 에 대해서는, 사실 서버나 클라이언트가 인증에 대한 정보를 갖고 있지 않는 상황이라 여기서 해주는 것이 좋을 것 같기는 한데 어떻게 생각하시나요? (구체적으로 어떻게 예외 처리를 해줄지는 생각을 좀 해봐야 겠지만...)
- 어짜피 컨트랙트 배포할 때 owner 가 서명할거니 did 를 저렇게 넘겨줘도 괜찮을 것 같다는 게 제 생각입니다..!

2022-03-04 12:40 UTC, 0JIEUN0 commented on contracts/Group.sol
> +           requesters[_requesterDid].isValid == false,
혹시 이게 이미 인증된 사용자인지 거르는 과정이면 true 인지 비교해야 하지 않나요?
인증되지 않은 사용자, 즉 초기에는 `isValid` 가 false 로 되어있어서요!

2022-03-04 12:40 UTC, 0JIEUN0 commented on contracts/Group.sol
> +           groupInfo.isValid == false,
여기도요! 확인 부탁드려요~!

2022-03-04 12:40 UTC, 0JIEUN0 commented on contracts/Group.sol
> +    Requester public groupInfo;
`groupInfo` 에도 `Requester` 라는 구조체를 사용한다면 `Requester` 라는 네이밍은 약간 어색해보이는데 어떻게 보시나요?

2022-03-04 12:40 UTC, 0JIEUN0 commented on contracts/Group.sol
> +           requesters[_approverDid].isValid == false,
이건 해당 did 가 이 그룹의 '승인된' user 인지 확인하는 것 아닌가요??

2022-03-04 13:06 UTC, Hongji0611 commented on contracts/Group.sol
> +           requesters[_requesterDid].isValid == false,
require가 아래 조건문에 만족해야지 본문을 실행한다 라고 이해했어요. 그래서 isValid가 false이어야 한다 라고 생각했습니다!

2022-03-04 13:20 UTC, Hongji0611 commented on contracts/Group.sol
> +    Requester public groupInfo;
동의합니다 둘을 통합할 수 있는 다른 네이밍 고민해보겠습니다!

2022-03-04 13:20 UTC, Hongji0611 commented on contracts/Group.sol
> +           groupInfo.isValid == false,
여기도 isValid가 true일때 이 함수를 실행하는 것이 아닌,
false일때 승인요청을 해야한다 라는 의미라서 저렇게 했습니다!

2022-03-04 13:20 UTC, Hongji0611 commented on contracts/Group.sol
> +           requesters[_approverDid].isValid == false,
넵 맞네요 주석을 승인된 유저인지 확인한다고 변경하겠습니다!
전체적으로 중복을 확인하는 방안을 위에 말씀하신 방법을 토대로 수정하겠습니다

2022-03-04 13:20 UTC, 0JIEUN0 commented on contracts/Group.sol
> +           groupInfo.isValid == false,
아 아예 true 면 걍 더이상 인증하지 않는 거군요 확인했습니다!

2022-03-06 18:30 UTC, mimwin commented on contracts/Group.sol
> +           requesters[_approverDid].isValid == false,
false가 아니라 true 가 되어야 하지 않나요??

2022-03-07 03:49 UTC, Hongji0611 commented on contracts/Group.sol
> +           requesters[_approverDid].isValid == false,
approveGroupAuthentication 함수는 그룹을 생성하고 난 뒤, 두 명의 유저 승인 이후 그룹 인증이 확인되는 구조 입니다.
여기서 이 그룹을 한번도 승인하지 않은 유저의 vaild를 false여야 하며, 그룹을 승인하고 난 뒤의 유저의 vaild는 아래와 마찬가지로 true로 변경됩니다. 즉, 이 함수에서는 isVaild 라는 변수가 그룹을 승인한 사람이 중복으로 승인을 해주었는지 확인해주는 용도로 사용됩니다.
따라서 require에는 유저의 vaild가 false여야 합니다 (그룹을 중복으로 승인하지 않았다는 의미, 만약 true라면 이 사람은 이미 그룹을 승인해줌)

(이전 코멘트에서 저도 헷갈려서 다시 의견 남깁니다!!)

2022-03-07 08:03 UTC, Hongji0611 commented on contracts/Group.sol
> +    Requester public groupInfo;
수정 완료👍

2022-03-08 02:26 UTC, 0JIEUN0 reviewed
수고하셨습니다! 
근데 혹시 requesters 가 결국 group member 이니 members 같은 이름은 어떤가요? 개인적으론 처음 봤을 때 헷갈렸는데 이대로가 더 의미에 맞다 하시면 그냥 이렇게 하구요!

2022-03-08 02:26 UTC, 0JIEUN0 commented on contracts/Group.sol
> +            requesters[_userDid].count == 0,
아 근데 solidity 에서 uint 값의 기본형이 0 이라 이건 모든 userdid 값에 대해서 통과되지 않나요??

2022-03-08 02:57 UTC, Hongji0611 commented on contracts/Group.sol
> +            requesters[_userDid].count == 0,
이미 회원인 사람이나, 가입을 대기 중인 사람을 걸러냅니다!

2022-03-08 03:39 UTC, 0JIEUN0 commented on contracts/Group.sol
> +            requesters[_userDid].count == 0,
아아아 그렇군요!

2022-03-08 03:39 UTC, 0JIEUN0 approved these changes

2022-03-08 10:12 UTC, 0JIEUN0 commented on contracts/Group.sol
> +        requesters[_userDid].isValid = false;
근데 `requestMember()` 에서 결국 해당 userdid 에 대한 `count` 랑 `isValid` 값을 변경해서 "이 사용자가 요청을 했다" 라는 것을 보는데, 사실 count 의 uint 와 isValid 의 bool 형의 default 값은 각각 0과 false 여서 `requestMember()` 를 거치지 않은 사용자도 동일한 값을 갖게 될텐데 이는 괜찮나요??

2022-03-08 10:22 UTC, Hongji0611 commented on contracts/Group.sol
> +        requesters[_userDid].isValid = false;
오호 그럴 수 있겠네요
그러면 members도 enum으로 바꾸겠습니다
(INVALID REQUEST WATING VALID) 2명의 승인이 필요한 구조!

2022-03-09 03:40 UTC, Hongji0611 commented on contracts/Group.sol
> +        requesters[_userDid].isValid = false;
@0JIEUN0 @mimwin  수정 완료!

2022-03-09 05:10 UTC, mimwin reviewed
고생 많았어요!!
처음 그룹이 만들어질 때 어떻게 되는지 궁금해서 코멘트 남겼습니다!

2022-03-09 05:10 UTC, mimwin commented on contracts/Group.sol
>      function requestMember(string memory _userDid) onlyValidGroup external{
처음 그룹이 만들어지고 나서, 그룹장을 제외한 나머지 두명은  `requestMember()` 를 통해 들어오게 되는거 같은데 ValidGroup이 아니라서 revert 되지 않을까요??

2022-03-09 05:10 UTC, mimwin commented on contracts/Group.sol
> +           members[_approverDid] != MemberStatus.VALID,
여기서 VALID가 아닌 user만 허용한다면, 그룹을 인증해줄 수 있는 사람은 상호인증이 되지 않은 사람들만 가능하게 되는건가요??
`approveMember()` 를 통해 상호인증을 마친 user는 members[_userDid] 값이 이미 VALID가 되어있다고 생각해서요!

2022-03-09 05:30 UTC, Hongji0611 commented on contracts/Group.sol
>      function requestMember(string memory _userDid) onlyValidGroup external{
아니요!! 처음 그룹이 만들어지고 나서 그룹의 승인을 위해서는 아래의 함수인 approveGroupAuthentication()을 통해 그룹을 승인하는 동시에 가입하게 됩니다. 즉 나머지 두 명은 따로 상호 인증을 거치지 않고 그룹을 인증하는 형태입니다.

2022-03-09 05:30 UTC, Hongji0611 commented on contracts/Group.sol
> +           members[_approverDid] != MemberStatus.VALID,
그래서 여기서 그룹을 승인하려는 사람이 VALID이면 이미 그룹을 승인한 사람이니까 이를 방지하기 위해서 VALID가 아닌 사람만 그룹 자체를 승인할 수 있다는 의미입니다.

2022-03-09 05:42 UTC, mimwin commented on contracts/Group.sol
>      function requestMember(string memory _userDid) onlyValidGroup external{
그럼 처음 두명은 requestMember 가 아닌 approveGroupAuthentication() 을 통해 가입되는 건가요??

2022-03-09 05:44 UTC, Hongji0611 commented on contracts/Group.sol
>      function requestMember(string memory _userDid) onlyValidGroup external{
넵넵 처음 두 명은 상호 인증은 하지 않지만, approveGroupAuthentication을 통해 그룹을 승인(서명)하는 동시에 가입되므로 여기서 그룹 장, 나머지 두 명을 인증한다고 생각했습니다!

2022-03-09 05:48 UTC, mimwin approved these changes

2022-03-09 05:53 UTC, merged