DID: register, check Id
A-APT/DuckBox-SmartContract pull request #4
Opened 2022-03-08 02:24 UTC by mimwin

### **개요**

- did 발급

### **상세내용**

- 사용자는 회원가입 할 때, `registerId()`를 호출하며 사용자의 DID가 필요합니다.
- 오직 자신의 계정만 삭제 가능합니다. 
- 계정은 누구나 참조할 수 있습니다.
- 회원가입 하는 경우 사용자의 isValid는 false 여야 합니다. 
- ids의 key 값 : DID, value 값 : Id 으로 매핑

2022-03-08 02:30 UTC, 0JIEUN0 requested changes

2022-03-08 02:30 UTC, 0JIEUN0 commented on contracts/DecentralizedId.sol
> +        ids[_id].addr = owner;
여기가 owner 면은 이 contract 주인의 address 가 되니 `msg.sender` 로 해야하지 않을까요?

2022-03-08 02:30 UTC, 0JIEUN0 commented on test/DecentralizedIdTest.js
> +    it("is_removeId_works_well", async ()m => {
요기 `m` 은 혹시 뭔가요??

2022-03-08 02:32 UTC, mimwin commented on test/DecentralizedIdTest.js
> +    it("is_removeId_works_well", async ()m => {
커밋 전에 잘못 들어갔나봅니다.. 수정할게요

2022-03-08 02:34 UTC, mimwin commented on contracts/DecentralizedId.sol
> +        ids[_id].addr = owner;
owner가 결국 msg.sender 라고 생각을 했는데 그건 contract 주인의 경우에만 해당되는 거였군요 
msg.sender 가 맞는거 같습니다

2022-03-08 03:37 UTC, 0JIEUN0 approved these changes
확인했습니다! 수고하셨습니다 👍👍

2022-03-08 03:42 UTC, Hongji0611 requested changes

2022-03-08 03:42 UTC, Hongji0611 commented on contracts/DecentralizedId.sol
> +        ids[_id].addr = msg.sender;
function 조건에 onlyOwner가 있는데, 그러면 msg.sender도 owner 아닌가요??
DID를 사용자가 바로 등록하려면 onlyOwner를 빼야 한다고 생각합니다!

(만약에 바꾼다면 아래 테스트코드도 다시 확인 부탁드려요!)

2022-03-08 03:43 UTC, 0JIEUN0 commented on contracts/DecentralizedId.sol
> +        ids[_id].addr = msg.sender;
오 그러네요 이건 제가 전에 onlyOwner 썼었던 거 같은데 여기선 없어야겠네요!

2022-03-09 02:38 UTC, mimwin commented on contracts/DecentralizedId.sol
> +        ids[_id].addr = msg.sender;
수정했습니다!

2022-03-09 03:25 UTC, Hongji0611 approved these changes

2022-03-09 03:27 UTC, merged